
pipeline {
  agent {
    dockerfile {
      dir 'automation'
      reuseNode true
      args '--network host'
    }
  }
  // agent any
  stages {
    stage('Deployment') {
      when {
        branch 'main'
      }
      steps {
        sh 'npm install'
        sh 'hugo'
        sshagent(credentials: ['documentation-buildfix']) {
          // Deploy to Apache webserver
          sh "rsync -r --delete --exclude 'content/projects/' --exclude static/fonts/univers public/ buildfix@documentation.irs.uni-stuttgart.de:/"
        }
      }
    }
  }
}
